export const productData = {
    products: [
        {
            name: "Gà dai nguyên con nhập khẩu đông lạnh túi 1.2kg",
            description:
                "Gà dai nhập khẩu được đóng gói và bảo quản theo những tiêu chuẩn nghiêm ngặt về vệ sinh và an toàn thực phẩm. Gà dai nguyên con nhập khẩu đông lạnh vẫn giữ được phần thịt gà dai, thơm, ngọt nên thường dùng để hầm nấu canh, súp hoặc cháo, giúp người dùng bảo quản lâu hơn.",
            category: "chicken",
            image: "https://cdn.tgdd.vn/Products/Images/8790/297314/bhx/ga-dai-nguyen-con-nhap-khau-dong-lanh-tui-12kg-202211100923418469.jpg",
            primaryPrice: 78000,
            oldPrice: 97000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Ba rọi heo C.P khay 500g",
            description:
                "Cánh giữa gà nhập khẩu tươi ngon, nhiều thịt, giàu dinh dưỡng thường dùng để chiên với nước mắm hoặc hấp hành. Cánh gà giữa nhập khẩu đông lạnh với phương pháp cấp đông hiện đại, giúp lưu giữ hương vị tự nhiên, mang đến những món ăn ngon cho gia đình.",
            category: "pork",
            image: "https://cdn.tgdd.vn/Products/Images/8790/297340/bhx/canh-ga-giua-nhap-khau-dong-lanh-tui-500g-9-11-mieng-202211220857256717.jpg",
            primaryPrice: 94000,
            oldPrice: 100000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Cốt lết heo G khay 300g (4-6 miếng )",
            description:
                "Cốt lết heo có xương G được đóng gói và bảo quản đạt các tiêu chuẩn về an toàn toàn thực phẩm. Bản thịt heo to, vân mỡ mỏng tạo độ béo nhẹ cho miếng thịt nên thường dùng để nướng, ram, chiên áp chảo.... Thịt heo G có thể dùng điện thoại quét mã QR trên tem sản phẩm để kiểm tra nguồn gốc.",
            category: "pork",
            image: "https://cdn.tgdd.vn/Products/Images/8781/241213/bhx/cot-let-heo-co-xuong-g-khay-300g-4-6-mieng-202203260859306872.jpg",
            primaryPrice: 38500,
            oldPrice: 50000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Cá lóc nguyên con làm sạch (300g - 450g/con)",
            description:
                "Cá lóc hay còn được gọi là cá quả, là một nguyên liệu quen thuộc thường xuất hiện trên bàn ăn của mỗi gia đình. Cá lóc có thịt ngọt, rất ngon, thích hợp làm nhiều món ăn hấp dẫn như bánh canh cá lóc, canh chua cá lóc, cá lóc kho tộ,... đảm bảo sẽ khiến cả nhà mê tít",
            category: "fish",
            image: "https://cdn.tgdd.vn/Products/Images/8782/268674/bhx/ca-loc-nguyen-con-lam-sach-300g-450g-con-202205260936069697.jpg",
            primaryPrice: 39000,
            oldPrice: 50000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Cá thu cắt khúc khay 300g (giao khúc giữa)",
            description:
                "Là một loại cá biển thơm ngon với thịt thơm và đầy bổ dưỡng. Cá thu giàu chất béo, chất đạm, giàu vitamin và khoáng chất cần thiết cho cơ thể. Cá thu được dùng nấu nhiều món ăn ngon như cá thu kho thơm, cá thu kho tiêu, cá thu kho nước dừa hấp dẫn. Cá thu Bách hoá XANH tươi ngon, nhập mới mỗi ngày.",
            category: "fish",
            image: "https://cdn.tgdd.vn/Products/Images/8782/274403/bhx/ca-thu-cat-khuc-khay-300g-giao-khuc-giua-202209150928185444.jpg",
            primaryPrice: 94800,
            oldPrice: 115000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Hộp 30 trứng cút tươi 4KFarm",
            description:
                "Hộp 30 trứng cút tươi 4KFarm từ thương hiệu trứng 4KFarm được đóng gói và bảo quản theo những tiêu chuẩn nghiêm ngặt về vệ sinh và an toàn thực phẩm, đảm bảo về chất lượng của thực phẩm. Trứng cút tròn, đều.Trứng cút thì bạn có thể luộc chín chế biến thành một số món ăn như: trứng cút hun khói,...",
            category: "egg",
            image: "https://cdn.tgdd.vn/Products/Images/8783/219097/bhx/hop-30-trung-cut-tuoi-vfarm-202211050921430956.jpg",
            primaryPrice: 27000,
            oldPrice: 27000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Hộp 30 trứng gà Happy Egg",
            description:
                "Hộp 30 trứng gà Happy Egg là một trong những thực phẩm dinh dưỡng quen thuộc, được sử dụng nhiều trong đời sống hằng ngày, dễ chế biến, chứa nhiều dưỡng chất. Trứng gà Happy Egg là thương hiệu trứng quen thuộc, uy tín và chất lượng",
            category: "egg",
            image: "https://cdn.tgdd.vn/Products/Images/8783/299272/bhx/hop-30-trung-ga-happy-egg-202212200905112326.jpg",
            primaryPrice: 89000,
            oldPrice: 90000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Tôm càng xanh khay 500g (10 - 15 con)",
            description:
                "Tôm là nguồn dinh dưỡng dồi dào, cung cấp hàm lượng canxi và sắt rất cao cho chế độ ăn hằng ngày. Khi thưởng thức, bạn sẽ cảm nhận phần thịt ngọt nước và hơi dai. Ngoài ra, tôm càng với kích thước to nên thường được dùng để trang trí các món ăn trong bữa tiệc hoặc bữa cơm gia đình.",
            category: "sea food",
            image: "https://cdn.tgdd.vn/Products/Images/8782/249433/bhx/tom-cang-khay-500g-5-10-con-202207221127390424.jpg",
            primaryPrice: 89000,
            oldPrice: 135000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Tôm sú nguyên con khay 500g (10 - 13 con)",
            description:
                "Tôm sú là loại thực phẩm quen thuộc, có thể chế biến thành nhiều món ăn ngon như luộc, hấp, nướng, các món lẩu,.... Thịt tôm sú dai dai, có vị ngọt rất hấp dẫn. Tôm sú tại Bách hoá XANH rất tươi ngon và được nhiều bà nội trợ chọn mua.",
            category: "sea food",
            image: "https://cdn.tgdd.vn/Products/Images/8782/285416/bhx/tom-su-nguyen-con-khay-500g-12-15-con-202208040850312165.jpg",
            primaryPrice: 129000,
            oldPrice: 150000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },

        {
            name: "Rau răm gói 100g",
            description:
                "Rau răm là một loại rau có vị cay, tính ấm và mùi thơm đặc trưng, thường ăn kèm với các món có tính hàn, giúp bụng của bạn tốt hơn. Rau răm thường dùng ăn kèm với hột vịt lộn, làm món đậu hũ kèm rau răm hay làm tăng gia vị cho các món kho, món gỏi,..",
            category: "vegetable",
            image: "https://cdn.tgdd.vn/Products/Images/8820/271503/bhx/rau-ram-goi-100g-202205190838444360.jpg",
            primaryPrice: 5500,
            oldPrice: 5500,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Xà lách lô lô xanh gói 500g",
            description:
                "Rau xà lách lô lô xanh của Bách hóa Xanh được trồng tại Lâm Đồng và đóng gói theo những tiêu chuẩn nghiêm ngặt, bảo đảm các tiêu chuẩn xanh - sach. Xà lách lô lô nhiều chất xơ, hàm lượng dinh dưỡng cao, vị ngọt, giòn nên thường dùng làm rau ăn kèm cho các món cuốn",
            category: "vegetable",
            image: "https://cdn.tgdd.vn/Products/Images/8820/271485/bhx/xa-lach-lo-lo-xanh-goi-500g-202205181607134610.jpg",
            primaryPrice: 19000,
            oldPrice: 21000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "3",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Dưa leo khay 500g (3 -5 trái)",
            description:
                "Dưa leo trái lớn tươi ngon, được trồng và thu hoạch đảm bảo chất lượng, an toàn cho sức khỏe người sử dụng. Trong dưa leo chứa nhiều chất xơ, vitamin C, E, K, magie,...dễ ăn, dễ phối trộn với các món ăn khác, tốt sức khỏe vừa mang lại hiệu quả làm đẹp rất tốt",
            category: "root vegetable",
            image: "https://cdn.tgdd.vn/Products/Images/8785/271512/bhx/dua-leo-vi-500g-3-5-trai-202205201600227798.jpg",
            primaryPrice: 12000,
            oldPrice: 11000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "1",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Cà chua túi 1kg (10 - 12 trái)",
            description:
                "Cà chua được trồng ở Lâm Đồng là loại rau củ rất tốt cho sức khoẻ của người sử dụng, loại rau củ này không những giúp bổ sung chất dinh dưỡng cần thiết cho cơ thể mà chúng có giúp làm đẹp da cho phái nữ. Cà chua có thể ăn sống hoặc chế biến các món ăn cũng rất ngon.",
            category: "root vegetable",
            image: "https://cdn.tgdd.vn/Products/Images/8785/271472/bhx/ca-chua-tui-1kg-10-12-trai-202205201608239644.jpg",
            primaryPrice: 30000,
            oldPrice: 35000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "1",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Táo Ninh Thuận hộp 1kg (25 - 30 trái)",
            description:
                "Táo xanh Ninh Thuận là trái cây đặc sản của vùng đất Phan Rang Ninh Thuận. Táo xanh hay táo ta, táo gai, tên khoa học Ziziphus mauritiana, là cây ăn quả nhiệt đới có nguồn gốc châu Phi. Khi ăn rửa sạch và ăn luôn vỏ, có vị ngọt thanh, giòn tan trong miệng. Quả ngon hơn khi chấm cùng muối ớt/muối tôm",
            category: "fruit",
            image: "https://cdn.tgdd.vn/Products/Images/8788/270218/bhx/tao-ninh-thuan-tui-1kg-25-30-trai-202211040906562481.jpg",
            primaryPrice: 30000,
            oldPrice: 39000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "1",
            exp: "01/01/2023",
            stock: 10,
        },
        {
            name: "Dưa hấu không hạt trái từ 2.8kg trở lên",
            description:
                "Dưa hấu không hạt là trái cây nhiều nước và các vitamin, khoáng chất cần thiết, đặc biệt là ít calo và chất béo. Dưa hấu được xem là một sản phẩm thay thế cho nước uống thông thường. Dưa ngọt khi trái tròn đều, cuống héo, xanh đậm có đầu vàng.",
            category: "fruit",
            image: "https://cdn.tgdd.vn/Products/Images/8788/272179/bhx/dua-hau-khong-hat-trai-tu-28kg-tro-len-202212071510232043.jpg",
            primaryPrice: 50000,
            oldPrice: 58000,
            origin: "Việt Nam",
            brand: "BachHoa.com",
            weight: "1",
            exp: "01/01/2023",
            stock: 10,
        },
    ],
};
